// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svjbirtueljnfsouhpoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2amJpcnR1ZWxqbmZzb3VocG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzcyOTMsImV4cCI6MjA2NDMxMzI5M30.TEgSmEZOgEJ5_eRhH5sOufrdemOb5GocePcqZbBwMoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
